[package]
name = "hopter_proc_macro"
version = "0.2.2"
edition = "2021"
license = "MIT"
description = "Procedural macro implementation for Hopter embedded operating system."
repository = "https://github.com/hopter-project/hopter-procedural-macro"
readme = false

[lib]
proc-macro = true

[features]
stm32f030 = []
stm32f030x4 = ["stm32f030"]
stm32f030x6 = ["stm32f030"]
stm32f030x8 = ["stm32f030"]
stm32f030xc = ["stm32f030"]
stm32f031 = []
stm32f038 = []
stm32f042 = []
stm32f048 = []
stm32f051 = []
stm32f058 = []
stm32f070 = []
stm32f070x6 = ["stm32f070"]
stm32f070xb = ["stm32f070"]
stm32f071 = []
stm32f072 = []
stm32f078 = []
stm32f091 = []
stm32f098 = []

stm32f401 = []
stm32f405 = []
stm32f407 = []
stm32f410 = []
stm32f411 = []
stm32f412 = []
stm32f413 = []
stm32f427 = []
stm32f429 = []
stm32f446 = []
stm32f469 = []

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
