[package]
name = "hopter_proc_macro"
version = "0.3.1"
edition = "2021"
license = "MIT"
description = "Procedural macro implementation for Hopter embedded operating system."
repository = "https://github.com/hopter-project/hopter-procedural-macro"
readme = false

[lib]
proc-macro = true

[features]
armv6m = []
armv7em = []

stm32f030 = ["armv6m"]
stm32f030x4 = ["stm32f030"]
stm32f030x6 = ["stm32f030"]
stm32f030x8 = ["stm32f030"]
stm32f030xc = ["stm32f030"]
stm32f031 = ["armv6m"]
stm32f038 = ["armv6m"]
stm32f042 = ["armv6m"]
stm32f048 = ["armv6m"]
stm32f051 = ["armv6m"]
stm32f058 = ["armv6m"]
stm32f070 = ["armv6m"]
stm32f070x6 = ["stm32f070"]
stm32f070xb = ["stm32f070"]
stm32f071 = ["armv6m"]
stm32f072 = ["armv6m"]
stm32f078 = ["armv6m"]
stm32f091 = ["armv6m"]
stm32f098 = ["armv6m"]

stm32f401 = ["armv7em"]
stm32f405 = ["armv7em"]
stm32f407 = ["armv7em"]
stm32f410 = ["armv7em"]
stm32f411 = ["armv7em"]
stm32f412 = ["armv7em"]
stm32f413 = ["armv7em"]
stm32f427 = ["armv7em"]
stm32f429 = ["armv7em"]
stm32f446 = ["armv7em"]
stm32f469 = ["armv7em"]

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
